name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sssnake_ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .[game]

      - name: Ruff check
        run: ruff check .

      - name: Black check
        run: black --check .

      - name: Mypy check
        run: mypy .

      - name: Run pytest with coverage
        run: pytest --cov=sssnake --cov-report=xml --cov-report=term-missing -q

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
          flags: unittests
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Build package
        run: | 
          python -m pip install --upgrade build
          python -m build --sdist --wheel

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sssnake-dist
          path: dist/*
      - name: Publish to TestPyPI
        if: startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}
        run: |
          python -m pip install --upgrade twine
          twine upload --repository testpypi dist/*